repositories:
  - name: postgresql
    url: https://charts.bitnami.com/bitnami
---
releases:
  - name: postgresql
    namespace: database
    chart: postgresql/postgresql
    version: 15.5.5
    installed: true
    values:
      - values.yaml
