# Default values for S3 Media Streamer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

nameOverride: ""
fullnameOverride: ""

image:
  registry: arturmon/s3stream
  pullPolicy: Always
  tag: latest

podAnnotations: {}
  # example: "key": "value"

podSecurityContext: {}
  # example:
  # runAsUser: 1000
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

port: 10000

service:
  type: ClusterIP
  metrics:
    enabled: true
    scheme: http
    path: /metrics

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  path: /metrics
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /metrics
  initialDelaySeconds: 10
  periodSeconds: 10

env:
  LOG_LEVEL: info
  S3_ACCESS_KEY_ID: app
  S3_SECRET_ACCESS_KEY: E7ct9Zr1rOu0ZJZLxTqv
  STORAGE_HOST: s3stream-postgresql
  SESSION_POSTGRESQL_HOST: s3stream-postgresql
  S3_ENDPOINT: s3stream-minio:9000
  MQ_BROKER: s3stream-rabbitmq
  CONSUL_URL: s3stream-consul-server:8500
  LOG_TYPE: gelf
  LOG_GELF_SERVER_URL: graylog.graylog.svc.cluster.local:12201
  OPEN_TELEMETRY_JAEGER_ENDPOINT: http://s3stream-jaeger-collector:4318
  CACHING_ENABLED: true
  CACHING_ADDRESS: s3stream-redis-headless:6379
  CACHING_PASSWORD: redis
  CACHING_EXPIRATION: 2


ingress:
  host: s3streammedia.localhost
  className: nginx
  useTls: false
  #annotations:
  #  cert-manager.io/cluster-issuer: letsencrypt-prod

nodeSelector: {}
# example: "kubernetes.io/hostname": "node1"

tolerations: []
  # example:
  # - key: "key1"
  #   operator: "Equal"
  #   value: "value1"
#   effect: "NoSchedule"

affinity: {}
  # example:
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/e2e-az-name
  #         operator: In
  #         values:
  #         - e2e-az1
#         - e2e-az2


prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.localhost
  prometheus-node-exporter:
    enabled: false
  extraScrapeConfigs: |
    - job_name: 'minio'
      metrics_path: /minio/v2/metrics/resource
      scrape_interval: 10s
      static_configs:
        - targets:
            - s3stream-minio:9000
    - job_name: 'minio-cluster'
      metrics_path: /minio/v2/metrics/cluster
      scrape_interval: 10s
      static_configs:
        - targets:
            - s3stream-minio:9000
    - job_name: 'minio-bucket'
      metrics_path: /minio/v2/metrics/bucket
      scrape_interval: 10s
      static_configs:
        - targets:
            - s3stream-minio:9000    
    

grafana:
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
  extraEmptyDirMounts:
  - name: provisioning
    mountPath: /etc/grafana/provisioning
  plugins:
    - grafana-piechart-panel
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://s3stream-prometheus-server
          access: proxy
          isDefault: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      k3s-stats:
        gnetId: 15282
        revision: 1
        datasource: Prometheus
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: Prometheus
      rabbitmq:
        gnetId: 10991
        revision: 14
        datasource: Prometheus
      Ingress-stats:
        gnetId: 14314
        revision: 2
        datasource: Prometheus
      consul:
        gnetId: 10890
        revision: 2
        datasource: Prometheus
      Go:
        gnetId: 6671
        revision: 2
        datasource: Prometheus
      postgres:
        gnetId: 9628
        revision: 7
        datasource: Prometheus
      minio-bucket:
        gnetId: 19237
        revision: 2
        datasource: Prometheus
      minio-cluster:
        gnetId: 13502
        revision: 26
        datasource: Prometheus
      minio-repl:
        gnetId: 15305
        revision: 5
        datasource: Prometheus


consul:
  global:
    datacenter: dc1
    metrics:
      enabled: true
      enableAgentMetrics: true
      enableHostMetrics: true
      enableTelemetryCollector: true
  server:
    replicas: 1
  telemetryCollector:
    enabled: true
  ui:
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: consul.localhost
          paths:
            - /
    metrics:
      provider: "prometheus"
      baseURL: http://prometheus-server
  dns:
    enabled: true


postgresql:
  auth:
    username: root
    password: 1qazxsw2
    postgresPassword: postgres
    database: db_issue_album
  metrics:
    enabled: true
  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE DATABASE session;
    persistence:
      size: 10Gi

redis:
  auth:
    password: "redis"

rabbitmq:
  auth:
    username: guest
    password: "guest"
  ingress:
    enabled: true
    hostname: rabbitmq.localhost
    ingressClassName: "nginx"
  metrics:
    enabled: true
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
        "users": [
          {
            "name": "guest",
            "password_hash": "BMfxN8drrYcIqXZMr+pWTpDT0nMcOagMduLX0bjr4jwud/pN",
            "hashing_algorithm": "rabbit_password_hashing_sha256",
            "tags": [
              "administrator"
            ],
            "limits": {}
          }
        ],
        "vhosts": [
          {
            "name": "/"
          }
        ],
        "permissions": [
          {
            "user": "guest",
            "vhost": "/",
            "configure": ".*",
            "write": ".*",
            "read": ".*"
          }
        ],
        "queues": [
          {
            "name": "s3_queue",
            "vhost": "/",
            "durable": true,
            "auto_delete": false,
            "arguments": {
              "x-queue-type": "classic"
            }
          }
        ],
        "exchanges": [
          {
            "name": "s3_exchange",
            "vhost": "/",
            "type": "fanout",
            "durable": true,
            "auto_delete": false,
            "internal": false,
            "arguments": {}
          }
        ],
        "bindings": [
          {
            "source": "s3_exchange",
            "vhost": "/",
            "destination": "s3_queue",
            "destination_type": "queue",
            "routing_key": "s3_queue",
            "arguments": {}
          }
        ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |-
    load_definitions = /app/load_definition.json
    

minio:
  auth:
    rootUser: admin
    rootPassword: "12345678"
  #defaultBuckets: "music-bucket"
  disableWebUI: false
  persistence:
    storageClass: "local-path"
    size: 20Gi
  extraEnvVars:
    - name: MINIO_NOTIFY_AMQP_ENABLE
      value: "on"
    - name: MINIO_NOTIFY_AMQP_URL
      value: "amqp://guest:guest@s3stream-rabbitmq:5672"
    - name: MINIO_NOTIFY_AMQP_EXCHANGE
      value: "s3_exchange"
    - name: MINIO_NOTIFY_AMQP_EXCHANGE_TYPE
      value: "fanout"
    - name: MINIO_NOTIFY_AMQP_DURABLE
      value: "on"
    - name: MINIO_NOTIFY_AMQP_DELIVERY_MODE
      value: "2"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio.localhost
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 999m
  apiIngress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio-api.localhost
  provisioning:
    enabled: true
    policies:
      - name: music-bucket-bucket-specific-policy
        statements:
          - resources:
              - "arn:aws:s3:::*"
            effect: "Allow"
            actions:
              - "s3:GetBucketLocation"
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:DeleteObject"
              - "s3:PutObject"
    config:
      - name: region
        options:
          name: us-east-1
    buckets:
      - name: music-bucket
        region: us-east-1
        versioning: Versioned
    users:
      - username: app
        password: E7ct9Zr1rOu0ZJZLxTqv
        disabled: false
        setPolicies: true
        policies:
          - music-bucket-bucket-specific-policy


jaeger:
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - jaeger.localhost
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false