###
GET http://localhost:10000/ping
Content-Type: application/json
###
GET http://localhost:10000/v1/albums
Content-Type: application/json
###
GET http://localhost:10000/v1/albums/I0001
Content-Type: application/json
###
POST http://localhost:10000/v1/albums/add
Content-Type: application/json

{
  "Title": "Test Titl1e",
  "Artist": "Test Artis22t1",
  "Price": 44.10,
  "Code": "I0001",
  "Description": "Description Test1",
  "Completed": false
}
###
POST http://localhost:10000/v1/albums/update
Content-Type: application/json

{
  "Title": "Marco Polo",
  "Artist": "Test Update",
  "Price": 123.99,
  "Code": "I0001",
  "Description": "Description Update",
  "Completed": false
}
###
DELETE http://localhost:10000/v1/albums/delete/I0001
Content-Type: application/json
###
DELETE http://localhost:10000/v1/albums/deleteAll
Content-Type: application/json
###
GET http://localhost:10000/metrics
Content-Type: application/json
###
POST http://localhost:10000/v1/users/register
Content-Type: application/json

{
  "email":"a@a.com",
  "name":"a",
  "password":"1",
  "role":"member"
}
###
POST http://localhost:10000/v1/users/login
Content-Type: application/json

{
  "email":"a@a.com",
  "password":"1"
}
###
POST http://localhost:10000/v1/users/login
Content-Type: application/json

{
  "email":"admin@admin.com",
  "password":"admin"
}
###
POST http://localhost:10000/v1/users/logout
Content-Type: application/json
###
GET http://localhost:10000/v1/users/me
Content-Type: application/json
###
POST http://localhost:10000/v1/users/delete
Content-Type: application/json

{
  "email":"a@a.com"
}
###
POST http://localhost:10000/v1/users/delete
Content-Type: application/json

{
  "email":"admin@admin.com"
}
###
GET http://localhost:10000/health
Content-Type: application/json