###-------------------------------------------------------SYSTEM------------------------------------------------
###
GET http://localhost:10000/ping
Content-Type: application/json
###
GET http://localhost:10000/metrics
Content-Type: application/json
###
GET http://localhost:10000/health
Content-Type: application/json
###---------------------------------------------------------JOB-------------------------------------------------
GET http://localhost:10000/job/status
Content-Type: application/json
###-------------------------------------------------------ALBUMS------------------------------------------------
###
GET http://localhost:10000/v1/tracks
Content-Type: application/json
###
GET http://localhost:10000/v1/tracks?page=1&page_size=10
Content-Type: application/json
###
GET http://localhost:10000/v1/tracks?page=1&page_size=10&sort_by=_id&sort_order=desc
Content-Type: application/json
###
### Postgresql LIKE filters (use _, %, \% )
GET http://localhost:10000/v1/tracks?page=1&page_size=10&sort_by=_id&sort_order=asc&filter=0127b619-be74-499c-97f8-c8748194d7fd
###
GET http://localhost:10000/v1/tracks?page=1&page_size=10&sort_by=_id&sort_order=asc&filter==0127b619-be74-499c-97f8-c8748194d7fd
Content-Type: application/json
###
GET http://localhost:10000/v1/tracks/0127b619-be74-499c-97f8-c8748194d7fd
Content-Type: application/json

###--------------------------------------------------------USERS------------------------------------------------
POST http://localhost:8080/v1/users/register
Content-Type: application/json

{
  "email":"a@a.com",
  "name":"a",
  "password":"1",
  "role":"member"
}
###
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email":"a@a.com",
  "password":"1"
}
###
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "email":"admin@admin.com",
  "password":"admin"
}
###
POST http://localhost:8080/v1/users/logout
Content-Type: application/json
###
GET http://localhost:10000/v1/users/me
Content-Type: application/json
###
POST http://localhost:10000/v1/users/delete
Content-Type: application/json

{
  "email":"a@a.com"
}
###
POST http://localhost:10000/v1/users/refresh
Content-Type: application/json

{
  "refresh_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTYzMzA0NTksInN1YiI6ImFAYS5jb20ifQ.5wejb-XaOpUvMPDP-JZRQET-HBcpJ5hDQVNN5A3A7y4"
}
###-------------------------------------------------------OTP------------------------------------------------
POST http://localhost:10000/v1/users/otp/generate
Content-Type: application/json

{
  "user_id":"cac22f72-1fa2-4a81-876d-39fcf1cc9159"
}
###
POST http://localhost:10000/v1/users/otp/verify
Content-Type: application/json

{
  "user_id":"cac22f72-1fa2-4a81-876d-39fcf1cc9159",
  "token": "946767"
}
###
POST http://localhost:10000/v1/users/otp/validate
Content-Type: application/json

{
  "user_id":"cac22f72-1fa2-4a81-876d-39fcf1cc9159",
  "token": "946767"
}
###
POST http://localhost:10000/v1/users/otp/disable
Content-Type: application/json

{
  "user_id":"cac22f72-1fa2-4a81-876d-39fcf1cc9159"
}

###-------------------------------------------------------PLAY LIST--------------------------------------------
### AddToPlaylist
POST http://localhost:10000/v1/playlist/79bb1214-ac3a-4233-9925-a9ed232dd320/add/track/679fcd2d-3eee-4f94-8989-06765b3b5426
Content-Type: application/json

### RemoveFromPlaylist
DELETE http://localhost:10000/v1/playlist/1e1dc1d2-d888-4d2d-b59e-ceb8f4e801c7/remove/track/89ffa57f-7186-4435-9604-cc21e9458489
Content-Type: application/json
### ClearPlaylist
DELETE http://localhost:10000/v1/playlist/1e1dc1d2-d888-4d2d-b59e-ceb8f4e801c7/clear
Content-Type: application/json

### CreatePlaylist
POST  http://localhost:10000/v1/playlist/create
Content-Type: application/json

{
  "level":"1",
  "title":"test Play list",
  "description":"test Play list"
}
### DeletePlaylist
DELETE http://localhost:10000/v1/playlist/delete/8ba3a3ac-b804-4220-b08f-b1d9f3931a9f
Content-Type: application/json
### SetFromPlaylist
POST http://localhost:10000/v1/playlist/8fe5434e-dc03-47f1-b358-2f83e7c7f4cf/set
Content-Type: application/json

{
  "track_order":
  [
    "3773f656-95f6-4a20-89f8-a9b05384b6ce",
    "6c47f7a4-fd91-44cb-a4a1-690c2e9f4381",
    "e75564f4-a1e7-4f91-8c0b-78131fd33268",
    "799712db-2784-438c-a29e-61820c46cebf",
    "dde313bb-8dd6-42ae-9abf-05cdf6fb2b7c",
    "f4237f6a-5769-4e42-b1aa-f2898ca86b8f",
    "76571608-f26d-4c5f-955d-f0d0a34b183f",
    "c70c2a37-3c52-4d27-a0d0-233e500773ae",
    "33521a1f-7cd3-4f00-932c-eecd3078d674",
    "007694c3-83a0-4f7b-97e9-21c3b8411fc8",
    "4a8988de-9d3a-4d5a-94e5-ac58d2e40cb1",
    "a807bbf0-43b9-4d3b-8f52-0afa0ab3a399",
    "09c6e8ef-667f-4aec-8713-dc3e2a7de982"

  ]
}

###-------------------------------------------------------PLAYER--------------------------------------------
### Play playlist
GET http://localhost:10000/v1/audio/930b1542-7f1f-4755-8c91-f19fb7c9eef4
Content-Type: application/json
