basePath: /v1
definitions:
  config.Album:
    properties:
      artist:
        example: Artist name
        type: string
      code:
        example: I001
        type: string
      description:
        example: A short description of the application
        type: string
      price:
        example: '{Number: 1.10, Currency: EUR}'
        type: string
      sender:
        example: amqp or rest
        type: string
      title:
        example: Title name
        type: string
    type: object
  config.User:
    description: 'User account information with: user _id, name, email, password'
    properties:
      email:
        example: aaaa@aaaa.com
        type: string
      password:
        example: "1111"
        type: string
    type: object
  gin.errorResponse:
    properties:
      message:
        type: string
    type: object
  gin.okLoginResponce:
    properties:
      email:
        type: string
      refresh_token:
        type: string
      role:
        type: string
    type: object
  gin.paramsRefreshTocken:
    properties:
      refresh_token:
        example: eyJhbGciOiJIU....FnjPC-zct_EDkIuUviRNI
        type: string
    type: object
  gin.responceRefreshTocken:
    properties:
      access_token:
        example: eyJhbGciOiJIU....FnjPC-zct_EDkIuUviRNI
        type: string
      refresh_token:
        example: eyJhbGciOiJIU....FnjPC-zct_EDkIuUviRNI
        type: string
    type: object
  gin.userResponse:
    properties:
      email:
        type: string
      name:
        type: string
      refresh_token:
        type: string
    type: object
  monitoring.HealthResponse:
    properties:
      status:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:10000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Sceleton Golang Application API
  version: 0.0.1
paths:
  /albums:
    get:
      consumes:
      - '*/*'
      description: responds with the list of all albums as JSON.
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Number of items per page
        in: query
        name: page_size
        required: true
        type: integer
      - description: Field to sort by (e.g., 'created_at')
        in: query
        name: sort_by
        type: string
      - description: Sort order ('asc' or 'desc')
        in: query
        name: sort_order
        type: string
      - description: Filter criteria
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/config.Album'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Show the list of all albums.
      tags:
      - album-controller
  /albums/{code}:
    get:
      consumes:
      - '*/*'
      description: |-
        locates the album whose ID value matches the id parameter sent by the client,
        then returns that album as a response.
      parameters:
      - description: Code album
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Album'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Album whose ID value matches the id.
      tags:
      - album-controller
  /albums/add:
    post:
      consumes:
      - application/json
      description: adds an album from JSON received in the request body.
      parameters:
      - description: Album details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/config.Album'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/config.Album'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Adds an album from JSON.
      tags:
      - album-controller
  /albums/delete/{code}:
    delete:
      consumes:
      - '*/*'
      description: locates the album whose ID value matches the id parameter and deletes
        it.
      parameters:
      - description: Code album
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Deletes album whose ID value matches the code.
      tags:
      - album-controller
  /albums/deleteAll:
    delete:
      consumes:
      - '*/*'
      description: Delete ALL.
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Complete removal of all albums.
      tags:
      - album-controller
  /albums/update:
    post:
      consumes:
      - application/json
      description: updates an existing album with new data based on the ID parameter
        sent by the client.
      parameters:
      - description: Updated album details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/config.Album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.Album'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Updates an existing album with new data.
      tags:
      - album-controller
  /health:
    get:
      consumes:
      - '*/*'
      description: Checks and returns the current health status of the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/monitoring.HealthResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/monitoring.HealthResponse'
      summary: Get health status of the application
      tags:
      - health-controller
  /ping:
    get:
      consumes:
      - '*/*'
      description: Check if the application server is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Application liveness check function
      tags:
      - health-controller
  /users/delete:
    delete:
      consumes:
      - application/json
      description: Deletes the authenticated user.
      produces:
      - application/json
      responses:
        "200":
          description: Success - User deleted
          schema:
            type: string
        "401":
          description: Unauthorized - User unauthenticated
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: Not Found - User not found
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Deletes a user.
      tags:
      - user-controller
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user with provided email and password.
      parameters:
      - description: Login User
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/config.User'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/gin.okLoginResponce'
        "400":
          description: Bad Request - Incorrect Password
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: Not Found - User not found
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      summary: Authenticates a user.
      tags:
      - user-controller
  /users/logout:
    post:
      consumes:
      - application/json
      description: Clears the authentication cookie, logging out the user.
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Logs out a user.
      tags:
      - user-controller
  /users/me:
    get:
      consumes:
      - '*/*'
      description: Retrieves user information based on JWT in the request's cookies
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/gin.okLoginResponce'
        "401":
          description: Unauthenticated
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user information
      tags:
      - user-controller
  /users/refresh:
    post:
      consumes:
      - application/json
      description: Validates the provided refresh token, generates a new access token,
        and returns it.
      parameters:
      - description: Refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          $ref: '#/definitions/gin.paramsRefreshTocken'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully refreshed access token
          schema:
            $ref: '#/definitions/gin.responceRefreshTocken'
        "400":
          description: Bad Request - Invalid refresh token
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "401":
          description: Unauthorized - Invalid refresh token
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      security:
      - ApiKeyAuth: []
      summary: Refreshes the access token using a valid refresh token.
      tags:
      - user-controller
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with provided name, email, and password.
      parameters:
      - description: Register User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/config.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gin.userResponse'
        "400":
          description: Bad Request - User with this email exists
          schema:
            $ref: '#/definitions/gin.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.errorResponse'
      summary: Registers a new user.
      tags:
      - user-controller
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
