apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | lower }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/Configmap.yaml") . | sha256sum }}
        {{- if .Values.service.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/scheme: {{ .Values.service.metrics.scheme | quote }}
        prometheus.io/path: {{ .Values.service.metrics.path | quote }}
        prometheus.io/port: {{ $.Values.port | quote }}
        {{- end }}
      labels:
        {{- include "labels" . | nindent 8 }}
        app.kubernetes.io/service: backend
    spec:
      terminationGracePeriodSeconds: 60 # put your longest Job time here plus security time.
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.registry }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http-backend
              containerPort: {{ $.Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "fullname" $ }}-env
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/metrics" }}
              port: {{ $.Values.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/metrics" }}
              port: {{ $.Values.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
