---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-service
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ $.Values.port }}
      targetPort: {{ $.Values.port }}
      protocol: TCP
      name: http-backend
  selector:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/service: backend

