BEGIN;

ALTER TABLE users
    ADD COLUMN Otp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users
    ADD COLUMN Otp_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users
    ADD COLUMN Otp_secret TEXT DEFAULT '';
ALTER TABLE users
    ADD COLUMN Otp_auth_url TEXT DEFAULT '';

COMMIT;
