BEGIN;

ALTER TABLE users
DROP COLUMN IF EXISTS Otp_enabled;
ALTER TABLE users
DROP COLUMN IF EXISTS Otp_verified;
ALTER TABLE users
DROP COLUMN IF EXISTS Otp_secret;
ALTER TABLE users
DROP COLUMN IF EXISTS Otp_auth_url;

COMMIT;
