repositories:
  - name: harbor
    url: https://helm.goharbor.io
---
releases:
  - name: harbor
    namespace: database
    chart: harbor/harbor
    version: v1.12.6
    installed: true
    values:
      - values.yaml
