helmDefaults:
  atomic: true
  wait: true

helmfiles:
  # observability
  - path: consul/helmfile.yaml
  # monitoring
  - path: prometheus/helmfile.yaml
  - path: grafana/helmfile.yaml
  - path: jaeger/helmfile.yaml
  # message
  - path: rabbitmq/helmfile.yaml
  # database
  - path: minio/helmfile.yaml
  - path: postgresql/helmfile.yaml
  - path: redis/helmfile.yaml
  - path: harbor/helmfile.yaml