{
 "title": "Consul Exporter Dashboard v2",
 "description": "Consul Exporter Dashboar for Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_catalog_services", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "Consul Peers and Leaders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "consul_raft_peers", "legendFormat": "peers" },
    { "expr": "consul_raft_leader", "legendFormat": "leader" },
    { "expr": "consul_serf_lan_members", "legendFormat": "serf_lan_members" }
   ]
  },
  {
   "title": "Unhealthy Consul Services",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, status) (consul_health_service_status{status!=\"passing\"})",
     "legendFormat": "{{service_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Unhealthy Consul Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_health_node_status{status!='passing'}",
     "legendFormat": "{{node}} - {{status}}"
    }
   ]
  },
  {
   "title": "Consul Services and Checks",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node,service_id,status) (consul_health_service_status)",
     "legendFormat": "{{node}} - {{service_id}} - {{status}}"
    }
   ]
  }
 ]
}