app_health: false

listen:
  bind_ip: "0.0.0.0"
  port: "10000"

consul:
  url: "localhost:8500"
  wait_time: 5

app_config:
  logs:
    level: "info" # debug, info, warn, error
    type: "json" # graylog, kafka, telegram, console, json
    graylog:
      server: "localhost:12201"
      compression_type: "none" # node, gzip, zlib
    kafka:
      brokers: "localhost:9092"
      type_connection: "udp"
      topic: "music-events"
      num_partitions: 1
      replication_factor: 1
      async: false
      max_attempts: 10
    telegram:
      token: "YOUR_TELEGRAM_BOT_TOKEN"
      chat_username: "YOUR_TELEGRAM_CHAT_ID"
  web:
    mode: "release" # debug, test, release
    debug:
      with_span_id: false
      with_trace_id: false
      with_request_body: false
      with_response_body: false
      with_request_header: false
      with_response_header: false
    corsAllowOrigins: "*" # example: http://localhost:10000 or *
  jobs:
    interval_rescan_consul: 60 #second
    job:
      - name: "s3Clean"
        start_job: "@every 10m"
      - name: "sessionClean"
        start_job: "@midnight"
      - name: "createNewMusicChart"
        start_job: "@daily"
  open_telemetry:
    tracing_enabled: true
    environment: "staging" # 'staging', 'production'
    jaeger_endpoint: "http://localhost:4318"
  s3:
    endpoint: "localhost:9000"
    access_key_id: "app"
    secret_access_key: ""
    use_ssl: false
    bucket_name: "music-bucket"
    location: "us-east-1"
  mdns:
    enabled: true

storage:
  caching:
    enabled: true
    address: "redis-master.database.svc.cluster.local:6379"
    password: "redis"
    expiration: 24 #Hours
  username: "root"
  password: "1qazxsw2"
  host: "postgresql.database.svc.cluster.local"
  port: "5432"
  database: "db_issue_album"

message_queue:
  sub_queue_name: "s3_queue"
  user: "guest"
  pass: "guest"
  broker: "localhost"
  broker_port: 5672
  retrying_connection: 5 # second
  subscribe_auto_ack: true

session:
  session_storage_type: "postgres" # cookie, memory, memcached, mongo, postgres
  session_name: "session"
  session_period_clean: "@midnight" # @midnight, */5 * * * *, @every 1h30m10s
  cookies:
    session_secret_key: "sdfgerfsd3543g"
  memcached:
    memcached_host: "localhost"
    memcached_port: "11211"
  mongodb:
    mongo_host: "localhost"
    mongo_port: "27017"
    mongo_database: "session"
    mongo_user: "root"
    mongo_pass: "1qazxsw2"
  postgresql:
    postgresql_host: "postgresql.database.svc.cluster.local"
    postgresql_port: "5432"
    postgresql_database: "session"
    postgresql_user: "root"
    postgresql_pass: "1qazxsw2"

otp:
  issuer: "example.com"
  secret_size: 15
