app_health: false

listen:
  bind_ip: "0.0.0.0"
  port: "10000"

consul:
  url: "localhost:8500"
  wait_time: 5

app_config:
  log_level: "debug" # otel, debug, info, warn, error, fatal, panic
  log_type: "text" # text, json, gelf
  log_gelf_server: "localhost:12201"
  log_gelf_server_type: "udp" # tcp, udp
  web:
    mode: "release" # debug, test, release
    corsAllowOrigins: "*" # example: http://localhost:10000 or *
  jobs:
    interval_rescan_consul: 60 #second
    job:
      - name: "s3Clean"
        start_job: "@every 10m"
      - name: "sessionClean"
        start_job: "@midnight"
  open_telemetry:
    tracing_enabled: true
    environment: "staging" # 'staging', 'production'
    jaeger_endpoint: "http://localhost:4318"
  s3:
    endpoint: "localhost:9000"
    access_key_id: "app"
    secret_access_key: ""
    use_ssl: false
    bucket_name: "music-bucket"
    location: "us-east-1"

storage:
  caching:
    enabled: true
    address: "localhost:6379"
    password: "redis"
    expiration: 24 #Hours
  username: "root"
  password: "1qazxsw2"
  host: "localhost"
  port: "5432"
  database: "db_issue_album"

message_queue:
  sub_queue_name: "s3_queue"
  user: "guest"
  pass: "guest"
  broker: "localhost"
  broker_port: 5672
  retrying_connection: 5 # second

session:
  session_storage_type: "postgres" # cookie, memory, memcached, mongo, postgres
  session_name: "session"
  session_period_clean: "@midnight" # @midnight, */5 * * * *, @every 1h30m10s
  cookies:
    session_secret_key: "sdfgerfsd3543g"
  memcached:
    memcached_host: "localhost"
    memcached_port: "11211"
  mongodb:
    mongo_host: "localhost"
    mongo_port: "27017"
    mongo_database: "session"
    mongo_user: "root"
    mongo_pass: "1qazxsw2"
  postgresql:
    postgresql_host: "localhost"
    postgresql_port: "5432"
    postgresql_database: "session"
    postgresql_user: "root"
    postgresql_pass: "1qazxsw2"

otp:
  issuer: "example.com"
  secret_size: 15
