auth:
  username: guest
  password: "guest"
ingress:
  enabled: true
  hostname: rabbitmq.localhost
  ingressClassName: "nginx"
metrics:
  enabled: true
extraSecrets:
  load-definition:
    load_definition.json: |
      {
      "users": [
        {
          "name": "guest",
          "password_hash": "BMfxN8drrYcIqXZMr+pWTpDT0nMcOagMduLX0bjr4jwud/pN",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": [
            "administrator"
          ],
          "limits": {}
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [
        {
          "name": "s3_queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-queue-type": "classic"
          }
        }
      ],
      "exchanges": [
        {
          "name": "s3_exchange",
          "vhost": "/",
          "type": "fanout",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "s3_exchange",
          "vhost": "/",
          "destination": "s3_queue",
          "destination_type": "queue",
          "routing_key": "s3_queue",
          "arguments": {}
        }
      ]
      }
loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |-
  load_definitions = /app/load_definition.json
