apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog
  labels:
    app: graylog
    release: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.graylog.host }}
      http:
        paths:
          - backend:
              service:
                name: graylog
                port:
                  number: 80
            path: /
            pathType: Prefix
