repositories:
  - name: minio
    url: https://charts.bitnami.com/bitnami
---
releases:
  - name: minio
    namespace: database
    chart: minio/minio
    version: 14.6.10
    installed: true
    values:
      - values.yaml
