adminUser: admin
adminPassword: admin
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.localhost
extraEmptyDirMounts:
  - name: provisioning
    mountPath: /etc/grafana/provisioning
plugins:
  - grafana-piechart-panel
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    k3s-stats:
      gnetId: 15282
      revision: 1
      datasource: Prometheus
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
    rabbitmq:
      gnetId: 10991
      revision: 14
      datasource: Prometheus
    Ingress-stats:
      gnetId: 14314
      revision: 2
      datasource: Prometheus
    consul:
      gnetId: 10890
      revision: 2
      datasource: Prometheus
    Go:
      gnetId: 6671
      revision: 2
      datasource: Prometheus
    postgres:
      gnetId: 9628
      revision: 7
      datasource: Prometheus
    minio-bucket:
      gnetId: 19237
      revision: 2
      datasource: Prometheus
    minio-cluster:
      gnetId: 13502
      revision: 26
      datasource: Prometheus
    minio-repl:
      gnetId: 15305
      revision: 5
      datasource: Prometheus
