global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: s3StreamPlayer
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 172.22.239.190:10000
  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187