global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187
  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269
  - job_name: rabbitmq-exporter
    static_configs:
      - targets:
          - rabbitmq:15692
  - job_name: haproxy
    metrics_path: /metrics
    static_configs:
      - targets:
          - haproxy:8404
  - job_name: consul
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - consul-exporter:9107
  - job_name: consul-discovery
    consul_sd_configs:
      - server: "consul:8500"
        tags: ["microservice","golang"]