definitions:
  main.album:
    properties:
      _id:
        type: string
      artist:
        type: string
      code:
        type: string
      completed:
        type: boolean
      created_at:
        type: string
      description:
        type: string
      price:
        type: number
      title:
        type: string
      updated_at:
        type: string
    type: object
  web.ResponseRequest:
    properties:
      message:
        type: string
    type: object
  web.getAllAlbums_other:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /albums:
    get:
      consumes:
      - '*/*'
      description: responds with the list of all albums as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.album'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Show the list of all album.
      tags:
      - album-controller
  /albums/:code:
    get:
      consumes:
      - '*/*'
      description: locates the album whose ID value matches the id parameter sent
        by the client, then returns that album as a response.
      parameters:
      - description: Code album
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.album'
        "400":
          description: We need Code!!
          schema:
            $ref: '#/definitions/web.getAllAlbums_other'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Album whose ID value matches the id.
      tags:
      - album-controller
    post:
      consumes:
      - '*/*'
      description: adds an album from JSON received in the request body.
      parameters:
      - description: Code
        in: path
        name: code
        required: true
        type: string
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.album'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/main.album'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Adds an album from JSON.
      tags:
      - album-controller
  /albums/delete/:code:
    get:
      consumes:
      - '*/*'
      description: locates the album whose ID value matches the id parameter delete.
      parameters:
      - description: Code album
        in: path
        name: code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ResponseRequest'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Album whose ID value matches the code and delete.
      tags:
      - album-controller
  /albums/deleteAll:
    get:
      consumes:
      - '*/*'
      description: Delete ALL.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ResponseRequest'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Complete removal of all albums.
      tags:
      - album-controller
  /ping:
    get:
      consumes:
      - '*/*'
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.ResponseRequest'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Application liveness check function
      tags:
      - album-controller
swagger: "2.0"
