global:
  enabled: false
  datacenter: dc1
  metrics:
    enabled: true
    enableAgentMetrics: true
    enableHostMetrics: true
    enableTelemetryCollector: true
server:
  enabled: true
  replicas: 1
telemetryCollector:
  enabled: false
ui:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: consul.localhost
        paths:
          - /
  metrics:
    provider: "prometheus"
    baseURL: http://prometheus-server.monitoring.svc.cluster.local
dns:
  enabled: true
connectInject:
  enabled: "-"
  default: false
