name: Clear cache

on:
  push:
    branches:
      - main
      - releases
jobs:
  clear:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:
      - uses: MyAlbum/purge-cache@v1
        with:
          max-age: 86400