name: Errors Check
on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'

jobs:
  golangci:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - run: reviewdog -version
