name: GHCR Cleanup Action
on:
  push:
    branches:
      - main
#  schedule:
#    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: ghcr.io cleanup action
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: true
          exclude-tags: v*
          keep-n-tagged: 10
          delete-untagged: true
          delete-ghost-images: true
          token: ${{ secrets.GITHUB_TOKEN }}