name: golangci-lint
on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
