name: CI/CD master

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
jobs:
  initial:
    name: Initialing
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: [1.18.x, 1.19]
        platform: [ubuntu-latest]
    steps: 
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Go modules Cache
      uses: actions/cache@v2
      id: go-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0

    - name: Test
      run: go test -race .

    - name: Build
      run: go build -v .
