name: CI/CD releases

on:
  push:
    branches: 
      - 'releases/**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches: 
      - 'releases/**'
    paths-ignore:
      - '**.md'

jobs:
  initial:
    name: Initialing
    runs-on: ${{ matrix.platform }}
    strategy:
      maxtrix:
        go-version: [1.18.x, 1.19]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps: 
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Go modules Cache
      uses: actions/cache@v3
      id: go-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download

  unit_tests:
    name: Unit test App
    runs-on: ubuntu-latest
    needs: initial
    steps:
    - name: Test
      run: go test -race ./...


  build:
    name: Building
    runs-on: ubuntu-latest
    needs: [initial, unit_tests]
    steps:
    - name: Build
      run: go build -v .